philippschwarzmueller/transcendence

Makefile, docker/redirect.sh, readme
Added a Makefile to run our docker setup + added a script to automatically redirect docker stuff into goinfre
=> Makefile + Docker Redirect

Makefile, backend/Dockerfile, backend/setup.sh, frontend/Dockerfile, frontend/setup.sh
Added a rule to automatically start docker
=> added docker autostart

Makefile, backend/Dockerfile, backend/setup.sh, docker-compose.yml, frontend/Dockerfile, frontend/setup.sh
- using npm install instead of npm ci
- using a single volume instead of 2, so we can unified types
- improved makefile open docker rule
=> Ft 29 docker setup

backend/package-lock.json, backend/package.json, backend/src/auth/auth.controller.ts, backend/src/auth/auth.module.ts, backend/src/auth/auth.service.ts, frontend/src/auth-provider.ts, frontend/src/routes/Login.tsx, frontend/src/routes/SignUp.tsx
[correct status code + pw hasing + http logic in controller
=> Ft 33 login returns wrong status on success

frontend/src/routes/Login.tsx, frontend/src/routes/SignUp.tsx
rm console.error in login.tsx +  input fields of login and signup clear after success.
=> Ft 34 clear signup form after submit

backend/src/auth/auth.service.ts, frontend/src/routes/Login.tsx, frontend/src/routes/SignUp.tsx
fix typo in error parsing (password != Password)
=> Ft 35 wrong error text on wrong password in frontend

backend/package-lock.json, backend/package.json, backend/src/auth/auth.controller.ts, backend/src/auth/auth.module.ts, backend/src/auth/auth.service.ts, docker-compose.yml, frontend/src/routes/Login.tsx
new button with which u can connect to 42intra and get back a token
=> Ft 36 get 42 json webtoken

backend/src/auth/auth.controller.ts, backend/src/auth/auth.service.ts, frontend/src/components/nav/Navbar.tsx, frontend/src/routes/Login.tsx
very very simple and crusty implementation of persisting the loggedin state using sessionStorage
=> Ft 16 persist session

backend/src/games/games.controller.ts, backend/src/games/games.module.ts, backend/src/games/games.service.ts, backend/src/games/properties.ts, frontend/src/components/gamewindow/Gamewindow.tsx, frontend/src/components/gamewindow/properties.ts
First implementation of a two player game. Right now limited to the same computer in two tabs
=> Ft 25 two player game

backend/src/games/games.gamelogic.ts, backend/src/games/games.service.ts
Improvemt of the paddle bounce logic.
Ball now no longer clips through the paddle and bounces at he edge, but bounces on the edge of the paddle.
Also restuctured GameLoop function by removing most of the logic parts and put them in a separate file, so the individual parts are easier to access
=> Ft 42 ball bounce improvement

frontend/src/index.tsx, frontend/src/routes/Profile.tsx
update the frontend to have routes for each user, redirect in case you're not logged in as an example and displaying the change settings button only when a user is on his own profile
=> add dynamic user profile routes to later fetch user profiles

backend/src/games/games.gamelogic.ts, backend/src/games/games.gateway.ts, backend/src/games/games.service.ts, backend/src/games/properties.ts, frontend/src/components/gamewindow/Gamewindow.tsx, frontend/src/components/gamewindow/properties.ts
Paddle position is now calculated in the backend instead of the frontend, so people cant cheat and multiple resolutions should work better in the future
=> Game: paddle movement now in backend

backend/src/games/games.gateway.ts, backend/src/games/games.service.ts, backend/src/games/properties.ts, frontend/src/components/gamewindow/Gamewindow.tsx, frontend/src/components/gamewindow/drawFunctions.ts, frontend/src/components/gamewindow/properties.ts
Added a clean way to leave the game, not nice but works
=> Ft 59 game crashed on leaving

backend/package-lock.json, backend/package.json, backend/src/auth/auth.controller.ts, backend/src/auth/auth.service.ts, backend/src/main.ts, backend/src/users/dto/create-user.dto.ts, backend/src/users/user.entity.ts, frontend/src/components/chatwindow/Chatwindow.tsx, frontend/src/context/auth.ts, frontend/src/index.tsx, frontend/src/routes/GetToken.tsx, frontend/src/routes/Home.tsx, frontend/src/routes/Login.tsx, frontend/src/routes/Profile.tsx, frontend/src/routes/SetUser.tsx
- intra logic exclusively moved into backend
- persistent cookie with hashed token in browser
- check function to test, if token is valid (expiry date / token in database?). currently linked with a button on homescreen.
=> Ft 69 codetoken42 interaction into backend

backend/src/games/games.service.ts
- Fixed a bug where another game entry got saved in to the db instead of updating the old one
- Added 'null' as placeholder for database games without a given name
=> Ft 104 game gets saved into db twice

frontend/src/components/gamecanvas/Gamecanvas.tsx, frontend/src/components/gamewindow/Gamewindow.tsx, frontend/src/components/gamewindow/drawFunctions.ts, frontend/src/components/gamewindow/keyboardinput.ts, frontend/src/components/gamewindow/properties.ts, frontend/src/components/gamewindow/windowresizing.ts
- Made the canvas size and all the drawings in the canvas scale wth the current window size
- removed old and unneccessary is game finished logic and replaced it with the other already implemented concept
- moved keyinput into other file to be more obvoius
- removed canvas border
=> Ft 97 make game responsive resizing

backend/src/chat/chat.service.ts
fixed chat not writing messages
=> fix gameaccept clause in print vanilla message

backend/src/auth/auth.controller.ts, backend/src/auth/auth.service.ts, backend/src/users/users.service.ts
- renaming to heilbronn 42 intranames is forbidden
- most of the logic moved from auth controller to service layer
=> namechange to heilbronn intranames forbidden

Makefile, backend/src/auth/auth.controller.ts, backend/src/auth/auth.service.ts, backend/src/main.ts, frontend/src/routes/Home.tsx, frontend/src/routes/Login.tsx, frontend/src/routes/PrivateRoute.tsx, frontend/src/routes/Profile.tsx, frontend/src/routes/ProfileSettings.tsx, frontend/src/routes/SetUser.tsx, frontend/src/routes/SignUp.tsx, setup_ip.sh
=> add backend variable

backend/src/users/users.service.ts, frontend/src/components/contextmenu/ContextMenu.tsx
after sending a friend request, the status is visible in context menu
=> Ft 131 add pending invite friendstate

backend/src/users/users.controller.ts, backend/src/users/users.service.ts, frontend/src/components/contextmenu/ContextMenu.tsx, frontend/src/components/profilepicture/ProfilePicture.tsx
restrictions for FriendState updates in the backend
=> FriendState restrictions in backend are in place

frontend/src/components/chatwindow/Chatwindow.tsx, frontend/src/components/elograph/elograph.tsx, frontend/src/components/matchhistory/Matchhistory.tsx, frontend/src/components/profilewindow/Profilewindow.tsx, frontend/src/components/stats/StatsWindow.tsx, frontend/src/components/userbrowser/Userbrowser.tsx, frontend/src/routes/SetUser.tsx
- rename name occurance with intraname
- catch a few uncatched fetches
=> Broken fetch

frontend/src/routes/SetUser.tsx
changed back to 2fa login component in setuser with last stable setuser state.
=> setuser back to 2fa login component

backend/src/users/dto/create-user.dto.ts, backend/src/users/user.entity.ts, backend/src/users/users.controller.ts, backend/src/users/users.service.ts, frontend/src/components/changeavatar/ChangeAvatar.tsx, frontend/src/components/playercard/Playercard.tsx, frontend/src/components/profilepicture/ProfilePicture.tsx, frontend/src/components/profilewindow/Profilewindow.tsx, frontend/src/components/taskbar/Taskbar.tsx, frontend/src/components/userbrowser/Userbrowser.tsx, frontend/src/context/auth.ts, frontend/src/routes/Profile.tsx, frontend/src/routes/SetUser.tsx
- switches between fallback and customAvatar works correctly
- profile picture and avatar component displays correctly
=> Custom avatar handling

frontend/src/components/changeavatar/ChangeAvatar.tsx, frontend/src/components/firstlogin/FirstLogin.tsx, frontend/src/components/leaderboard/leaderboard.tsx, frontend/src/components/outlinecontainer/outlinecontainer.tsx, frontend/src/components/profilepicture/ProfilePicture.tsx, frontend/src/components/profilesettings/Profilesettings.tsx, frontend/src/components/profilewindow/Profilewindow.tsx
- fixing wrong position of outline container title
- fixing profile picture size
- merged logic from micha for custom avatars
=> Ft 138 profile profile settings bugfix

frontend/src/components/leaderboard/leaderboard.tsx, frontend/src/components/matchhistory/Matchhistory.tsx
=> Ft 142 broken navigate links in matchhistory

backend/src/users/users.controller.ts, backend/src/users/users.service.ts, frontend/src/components/contextmenu/ContextMenu.tsx
after receiving a friend request the user is now able to deny the request instead of accepting it
=> Ft 153 option to deny friend request

backend/src/chat/chat.dao.ts, backend/src/chat/chat.service.ts, backend/src/chat/chat.servicebase.ts, backend/src/users/users.service.ts, frontend/src/components/chatwindow/Chatwindow.tsx, frontend/src/components/popup/Popup.tsx
=> Fix chat rendering

frontend/src/components/chatwindow/Chatwindow.tsx, frontend/src/components/friendbrowser/Friendbrowser.tsx, frontend/src/components/gameicon/Gameicon.tsx, frontend/src/components/leaderboard/leaderboard.tsx, frontend/src/components/moveablewindow/Moveablewindow.tsx, frontend/src/components/profilesettings/Profilesettings.tsx, frontend/src/components/profilewindow/Profilewindow.tsx, frontend/src/components/spectatorboard/spectatorboard.tsx, frontend/src/components/taskbar/Taskbar.tsx, frontend/src/components/userbrowser/Userbrowser.tsx, frontend/src/context/profile.tsx, frontend/src/routes/root.tsx
=> Exit button

backend/src/auth/auth.service.ts, backend/src/chat/chat.service.ts, backend/src/chat/chat.servicebase.ts, frontend/src/components/chatwindow/Chatwindow.tsx, frontend/src/components/popup/Popup.tsx
=> fix 2u2 chat when names changed
